version: "3"

services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "url_shortener_db"
      POSTGRES_USER: "url_shortener_user"
      POSTGRES_PASSWORD: ""
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  database:
    build: database/
#    command:
    network_mode: host

  backend:
    build: backend/
    command:
      - ./url_shorter
    ports:
      - "8000:8000"
    depends_on:
      - database

